name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -yq libboost-dev
      
    - name: Configure CMake
      run: mkdir build && cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
      env:
        CXX:  g++-13
        
    - name: Build
      run: cmake --build ${{github.workspace}}/build
    
    - name: install
      run: sudo cmake --install ${{github.workspace}}/build
    
